services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: ai-crm-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      MONGO_URI: mongodb://mongo:27017/ai_crm?replicaSet=rs0
      REDIS_URL: redis://redis:6379

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      mongo-init:
        condition: service_completed_successfully
      redis:
        condition: service_started

    restart: unless-stopped


  mongo:
    image: mongo:8

    container_name: ai-crm-mongo

    command:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all

    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"]
      interval: 5s
      timeout: 5s
      retries: 20

    ports:
      - "27018:27017"

    volumes:
      - mongo_data:/data/db

    restart: unless-stopped


  mongo-init:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    command:
      - mongosh
      - --host
      - mongo:27017
      - --eval
      - "try { const config = rs.conf(); if (config.members[0].host !== 'mongo:27017') { config.members[0].host = 'mongo:27017'; rs.reconfig(config, {force: true}) } } catch (error) { rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]}) }"


  redis:
    image: redis:7

    container_name: ai-crm-redis

    ports:
      - "6379:6379"

    restart: unless-stopped


volumes:
  mongo_data: